# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://zac-kornberg.github.io/
title: Zac's Website
email: zakornbe@uwaterloo.ca
author: Zachary Kornberg
description: > # "Write an awesome description for your new site here. 
  A look at my projects
copyright: 'Copyright &copy; 2015 Zachary Kornberg. All Rights Reserved.'
credits: 'Credits: Zachary Kornberg'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: nta
  - title: github
    url: https://github.com/Zac-Kornberg
  - title: linkedin
    url: https://www.linkedin.com/in/zac-kornberg/
